"""Tests for ``smsf_screener.py``.

Everything here runs offline against synthetic fixtures generated by
``tools/make_smsf_fixtures.py``. No test asserts a fact about a real product;
the real ``smsf_universe.csv`` is only checked for internal consistency.

The autouse ``sandbox`` fixture in conftest.py blocks the network and moves
the working directory to a temp dir, which is why fixture paths are absolute.
"""

import importlib.util
import io
import json
import sys
from datetime import date, timedelta
from pathlib import Path

import pytest

PROJECT_DIR = Path(__file__).resolve().parent.parent
FIXTURE_DIR = PROJECT_DIR / "tests" / "fixtures" / "smsf"
UNIVERSE = FIXTURE_DIR / "universe.csv"
REAL_UNIVERSE = PROJECT_DIR / "smsf_universe.csv"
TODAY = date(2026, 9, 6)
AS_OF = date(2026, 9, 4)


def _load():
    spec = importlib.util.spec_from_file_location("smsf_screener", PROJECT_DIR / "smsf_screener.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


ss = _load()


@pytest.fixture(scope="module")
def universe():
    return ss.load_universe(str(UNIVERSE))


@pytest.fixture(scope="module")
def screened(universe):
    return ss.screen(universe, str(FIXTURE_DIR), dict(ss.DEFAULT_FILTERS), TODAY, as_of=AS_OF,
                     parcels=(10_000.0, 25_000.0), brokerage_aud=10.0)


def by_ticker(screened, ticker):
    for e in screened["results"]:
        if e["product"]["ticker"] == ticker:
            return e
    raise KeyError(ticker)


# ---------------------------------------------------------------------------
# Pure arithmetic
# ---------------------------------------------------------------------------

class TestGrossedUpYield:
    def test_fully_franked_at_30pct(self):
        gross, credit = ss.grossed_up_yield(4.0, 100.0)
        assert gross == pytest.approx(4.0 * (1 + 0.3 / 0.7))
        assert credit == pytest.approx(gross - 4.0)

    def test_unfranked_is_unchanged(self):
        assert ss.grossed_up_yield(4.0, 0.0) == (4.0, 0.0)

    def test_half_franked(self):
        gross, _ = ss.grossed_up_yield(4.0, 50.0)
        assert gross == pytest.approx(4.0 + 4.0 * 0.5 * 0.3 / 0.7)

    @pytest.mark.parametrize("franking", [-1, 101])
    def test_rejects_bad_franking(self, franking):
        with pytest.raises(ss.ScreenerError):
            ss.grossed_up_yield(4.0, franking)

    def test_rejects_bad_tax_rate(self):
        with pytest.raises(ss.ScreenerError):
            ss.grossed_up_yield(4.0, 100.0, tax_rate=1.0)


class TestMinimumDrawdown:
    @pytest.mark.parametrize("age,factor", [
        (55, 4.0), (60, 4.0), (64, 4.0), (65, 5.0), (74, 5.0), (75, 6.0), (79, 6.0),
        (80, 7.0), (84, 7.0), (85, 9.0), (89, 9.0), (90, 11.0), (94, 11.0), (95, 14.0), (105, 14.0),
    ])
    def test_schedule_7_bands(self, age, factor):
        assert ss.minimum_drawdown_factor(age) == factor

    def test_negative_age_rejected(self):
        with pytest.raises(ss.ScreenerError):
            ss.minimum_drawdown_factor(-1)


class TestParcelPlan:
    def test_whole_units_after_brokerage(self):
        plan = ss.parcel_plan(95.0, 10_000.0, 10.0)
        assert plan["units"] == 105              # floor(9990 / 95)
        assert plan["value_aud"] == pytest.approx(9975.0)
        assert plan["total_cost_aud"] == pytest.approx(9985.0)
        assert plan["leftover_aud"] == pytest.approx(15.0)
        assert plan["marketable"] is True
        assert plan["brokerage_pct"] == pytest.approx(10.0 / 9975.0 * 100)

    def test_unit_price_above_parcel_buys_nothing(self):
        plan = ss.parcel_plan(30_000.0, 10_000.0, 10.0)
        assert plan["units"] == 0
        assert plan["marketable"] is False
        assert plan["total_cost_aud"] == 0.0
        assert plan["leftover_aud"] == 10_000.0
        assert plan["brokerage_pct"] is None

    def test_brokerage_larger_than_parcel(self):
        plan = ss.parcel_plan(10.0, 5.0, 10.0)
        assert plan["units"] == 0

    def test_below_marketable_parcel_flagged(self):
        plan = ss.parcel_plan(400.0, 600.0, 0.0)
        assert plan["units"] == 1 and plan["marketable"] is False

    @pytest.mark.parametrize("price,parcel,brokerage", [(0, 100, 0), (-1, 100, 0), (10, 0, 0), (10, 100, -1)])
    def test_rejects_bad_inputs(self, price, parcel, brokerage):
        with pytest.raises(ss.ScreenerError):
            ss.parcel_plan(price, parcel, brokerage)


# ---------------------------------------------------------------------------
# Metrics from history
# ---------------------------------------------------------------------------

def _rows(start, closes, volume=1000):
    return [{"date": start + timedelta(days=i), "close": c, "volume": volume} for i, c in enumerate(closes)]


class TestComputeMetrics:
    def test_flat_series_has_zero_vol_and_drawdown(self):
        rows = _rows(date(2025, 1, 1), [50.0] * 300)
        m = ss.compute_metrics(rows, [], date(2025, 12, 31))
        assert m["has_prices"]
        assert m["vol_pct"] == pytest.approx(0.0)
        assert m["mdd_pct"] == pytest.approx(0.0)
        assert m["adv_aud"] == pytest.approx(50_000.0)
        assert m["cash_yield_pct"] == 0.0
        assert m["ttm_dist_count"] == 0

    def test_drawdown_is_worst_fall_from_peak(self):
        rows = _rows(date(2025, 1, 1), [100, 120, 90, 110, 60, 80])
        m = ss.compute_metrics(rows, [], date(2025, 1, 6))
        assert m["mdd_pct"] == pytest.approx(50.0)   # 120 -> 60

    def test_rows_after_as_of_are_ignored(self):
        rows = _rows(date(2025, 1, 1), [100, 100, 100, 1])
        m = ss.compute_metrics(rows, [], date(2025, 1, 3))
        assert m["last_price"] == 100 and m["mdd_pct"] == 0.0

    def test_no_rows_on_or_before_as_of(self):
        rows = _rows(date(2025, 6, 1), [100, 100])
        assert ss.compute_metrics(rows, [], date(2025, 1, 1)) == {"has_prices": False}

    def test_ttm_window_is_half_open(self):
        as_of = date(2026, 3, 1)
        rows = _rows(as_of - timedelta(days=400), [100.0] * 401)
        dists = [
            {"date": as_of - timedelta(days=365), "amount": 5.0},   # exactly a year ago: out
            {"date": as_of - timedelta(days=364), "amount": 1.0},   # in
            {"date": as_of, "amount": 2.0},                          # on as-of: in
            {"date": as_of + timedelta(days=1), "amount": 7.0},     # future: out
        ]
        m = ss.compute_metrics(rows, dists, as_of)
        assert m["ttm_dist_per_unit"] == pytest.approx(3.0)
        assert m["ttm_dist_count"] == 2
        assert m["cash_yield_pct"] == pytest.approx(3.0)

    def test_total_return_uses_price_a_year_ago_plus_distributions(self):
        as_of = date(2026, 3, 1)
        closes = [100.0] * 366 + [110.0] * 35
        rows = _rows(as_of - timedelta(days=400), closes)
        m = ss.compute_metrics(rows, [{"date": as_of, "amount": 4.0}], as_of)
        assert m["total_return_1y_pct"] == pytest.approx(14.0)

    def test_short_history_leaves_vol_unknown(self):
        rows = _rows(date(2026, 8, 1), [100 + i for i in range(10)])
        m = ss.compute_metrics(rows, [], date(2026, 8, 10))
        assert m["vol_pct"] is None and m["adv_aud"] is None
        assert m["mdd_pct"] == pytest.approx(0.0)

    def test_volatility_is_annualised_stdev_of_log_returns(self):
        import math
        import statistics
        closes = [100.0]
        for i in range(60):
            closes.append(closes[-1] * (1.01 if i % 2 else 0.99))
        rows = _rows(date(2026, 1, 1), closes)
        m = ss.compute_metrics(rows, [], date(2026, 3, 1))
        rets = [math.log(b / a) for a, b in zip(closes, closes[1:])]
        assert m["vol_pct"] == pytest.approx(statistics.stdev(rets) * math.sqrt(252) * 100)


# ---------------------------------------------------------------------------
# Loading and validating input files
# ---------------------------------------------------------------------------

class TestLoadUniverse:
    def test_fixture_universe_loads(self, universe):
        assert {p["ticker"] for p in universe} >= {"CASHX", "AUEQX", "NODATA"}
        assert all(p["role"] in ss.ROLES for p in universe)

    def test_real_universe_loads_and_is_internally_consistent(self):
        products = ss.load_universe(str(REAL_UNIVERSE))
        assert len(products) >= 30
        assert ss.audit_universe(products, TODAY) == []
        assert all(p["as_at"] <= TODAY for p in products)

    def _write(self, tmp_path, text):
        path = tmp_path / "u.csv"
        path.write_text(text)
        return str(path)

    HEADER = ",".join(ss.UNIVERSE_COLUMNS) + "\n"
    GOOD = "VAS,Name,Vanguard,etf,core_au,cat,growth,0.07,20000,75,quarterly,na,,2026-06-30\n"

    def test_missing_column(self, tmp_path):
        with pytest.raises(ss.ScreenerError, match="missing columns"):
            ss.load_universe(self._write(tmp_path, "ticker,name\nVAS,x\n"))

    def test_bad_role(self, tmp_path):
        bad = self.GOOD.replace("core_au", "moon")
        with pytest.raises(ss.ScreenerError, match="role"):
            ss.load_universe(self._write(tmp_path, self.HEADER + bad))

    def test_duplicate_ticker(self, tmp_path):
        with pytest.raises(ss.ScreenerError, match="duplicate"):
            ss.load_universe(self._write(tmp_path, self.HEADER + self.GOOD + self.GOOD))

    def test_franking_out_of_range(self, tmp_path):
        bad = self.GOOD.replace(",75,", ",120,")
        with pytest.raises(ss.ScreenerError, match="franking_pct"):
            ss.load_universe(self._write(tmp_path, self.HEADER + bad))

    def test_bad_date(self, tmp_path):
        bad = self.GOOD.replace("2026-06-30", "30/06/2026")
        with pytest.raises(ss.ScreenerError, match="as_at"):
            ss.load_universe(self._write(tmp_path, self.HEADER + bad))

    def test_ticker_is_upper_cased_and_validated(self, tmp_path):
        products = ss.load_universe(self._write(tmp_path, self.HEADER + self.GOOD.replace("VAS", "vas")))
        assert products[0]["ticker"] == "VAS"
        with pytest.raises(ss.ScreenerError, match="ASX code"):
            ss.load_universe(self._write(tmp_path, self.HEADER + self.GOOD.replace("VAS", "TOO-LONG")))

    def test_missing_file(self, tmp_path):
        with pytest.raises(ss.ScreenerError, match="not found"):
            ss.load_universe(str(tmp_path / "nope.csv"))

    def test_empty_file(self, tmp_path):
        with pytest.raises(ss.ScreenerError, match="no products"):
            ss.load_universe(self._write(tmp_path, self.HEADER))


class TestAuditUniverse:
    def _product(self, **over):
        base = dict(ticker="T", name="Fund", issuer="X", structure="etf", role="core_au", category="c",
                    asset_class="growth", mer_pct=0.1, size_aud_m=1000, franking_pct=75,
                    distribution_frequency="quarterly", hedged=None, notes="", as_at=date(2026, 6, 30))
        base.update(over)
        return base

    def test_clean_product_has_no_findings(self):
        assert ss.audit_universe([self._product()], TODAY) == []

    def test_hedged_name_but_unhedged_flag(self):
        f = ss.audit_universe([self._product(name="Global (Hedged) ETF", hedged=False)], TODAY)
        assert any("hedged" in x for x in f)

    def test_franking_on_bond_fund(self):
        f = ss.audit_universe([self._product(role="defensive", asset_class="defensive", franking_pct=40)], TODAY)
        assert any("implausible" in x for x in f)

    def test_hybrid_franking_is_allowed(self):
        p = self._product(role="defensive", asset_class="defensive", structure="hybrid_etf", franking_pct=45)
        assert ss.audit_universe([p], TODAY) == []

    def test_stale_and_future_dates(self):
        old = self._product(as_at=TODAY - timedelta(days=ss.STATIC_STALE_DAYS + 1))
        future = self._product(ticker="U", as_at=TODAY + timedelta(days=1))
        f = ss.audit_universe([old, future], TODAY)
        assert any("days old" in x for x in f) and any("future" in x for x in f)

    def test_zero_mer_and_tiny_size(self):
        f = ss.audit_universe([self._product(mer_pct=0, size_aud_m=1)], TODAY)
        assert any("MER is 0" in x for x in f) and any("millions" in x for x in f)


class TestLoadHistory:
    def test_missing_price_file_is_none(self, tmp_path):
        assert ss.load_price_history(str(tmp_path), "ZZZ") is None
        assert ss.load_distributions(str(tmp_path), "ZZZ") == []

    def test_blank_and_duplicate_rows(self, tmp_path):
        (tmp_path / "T.csv").write_text(
            "Date,Close,Volume\n2026-01-02,10,100\n2026-01-03,,\n2026-01-02,11,50\n2026-01-05,12,\n")
        rows = ss.load_price_history(str(tmp_path), "T")
        assert [(r["date"].isoformat(), r["close"], r["volume"]) for r in rows] == [
            ("2026-01-02", 11.0, 50.0), ("2026-01-05", 12.0, 0.0)]

    def test_missing_close_column(self, tmp_path):
        (tmp_path / "T.csv").write_text("date,price\n2026-01-02,10\n")
        with pytest.raises(ss.ScreenerError, match="close"):
            ss.load_price_history(str(tmp_path), "T")

    def test_negative_close_rejected(self, tmp_path):
        (tmp_path / "T.csv").write_text("date,close,volume\n2026-01-02,-10,1\n")
        with pytest.raises(ss.ScreenerError, match="close"):
            ss.load_price_history(str(tmp_path), "T")

    def test_dividends_skip_zero_and_blank(self, tmp_path):
        (tmp_path / "T.dividends.csv").write_text("date,amount\n2026-01-02,0\n2026-02-02,\n2026-03-02,0.5\n")
        assert ss.load_distributions(str(tmp_path), "T") == [{"date": date(2026, 3, 2), "amount": 0.5}]


# ---------------------------------------------------------------------------
# Screening the fixture universe
# ---------------------------------------------------------------------------

class TestScreen:
    def test_as_of_defaults_to_newest_price_date(self, universe):
        s = ss.screen(universe, str(FIXTURE_DIR), dict(ss.DEFAULT_FILTERS), TODAY)
        assert s["as_of"] == AS_OF

    def test_cheaper_bigger_cash_fund_ranks_first(self, screened):
        assert by_ticker(screened, "CASHX")["rank_in_role"] == 1
        assert by_ticker(screened, "CASHY")["rank_in_role"] == 2

    @pytest.mark.parametrize("ticker,fragment", [
        ("HYBX", "APRA"),
        ("PRICY", "MER 0.35% is above"),
        ("TINYX", "fund size"),
        ("THINX", "median daily value traded"),
        ("STALE", "days older than the as-of date"),
        ("NODATA", "no price history"),
    ])
    def test_exclusions_carry_reasons(self, screened, ticker, fragment):
        e = by_ticker(screened, ticker)
        assert any(fragment in r for r in e["exclusions"]), e["exclusions"]
        assert e["rank_in_role"] is None

    def test_allow_hybrids_flag(self, universe):
        filters = dict(ss.DEFAULT_FILTERS, allow_hybrids=True)
        s = ss.screen(universe, str(FIXTURE_DIR), filters, TODAY, as_of=AS_OF)
        assert by_ticker(s, "HYBX")["exclusions"] == []

    @pytest.mark.parametrize("ticker,fragment", [
        ("HIYLD", "unusually high"),
        ("LICX", "premium or discount to NTA"),
        ("OLDFCT", "static facts dated 2025-01-01"),
        ("RICHX", "marketable minimum"),
        ("HIYLD", "active fund"),
    ])
    def test_warnings(self, screened, ticker, fragment):
        e = by_ticker(screened, ticker)
        assert any(fragment in w for w in e["warnings"]), e["warnings"]

    def test_suspicious_yield_is_not_rewarded(self, screened):
        e = by_ticker(screened, "HIYLD")
        assert e["metrics"]["cash_yield_pct"] > ss.YIELD_SANITY_CAP_PCT
        assert e["score"]["components"]["income"] == 50.0
        assert any("unverified" in n for n in e["score"]["notes"])
        # The same product with a sane yield would have scored full income points.
        sane = dict(e["metrics"], cash_yield_pct=8.0)
        assert ss.score_product(e["product"], sane)["components"]["income"] == 100.0

    def test_survivors_have_no_yield_warning(self, screened):
        e = by_ticker(screened, "AUEQX")
        assert not any("unusually high" in w for w in e["warnings"])

    def test_ranks_follow_scores_within_each_role(self, screened):
        for role in ss.ROLES:
            survivors = [e for e in screened["results"] if e["product"]["role"] == role and not e["exclusions"]]
            scores = [e["score"]["total"] for e in survivors]
            assert scores == sorted(scores, reverse=True)
            assert [e["rank_in_role"] for e in survivors] == list(range(1, len(survivors) + 1))

    def test_score_components_are_bounded_and_weighted(self, screened):
        for e in screened["results"]:
            if not e["score"]:
                continue
            s = e["score"]
            assert sum(s["weights"].values()) == 100
            assert all(0 <= v <= 100 for v in s["components"].values())
            expected = sum(s["weights"][k] * s["components"][k] for k in s["components"]) / 100
            assert s["total"] == pytest.approx(expected, abs=0.15)

    def test_gross_yield_reflects_franking(self, screened):
        au = by_ticker(screened, "AUEQX")
        intl = by_ticker(screened, "INTLX")
        assert au["score"]["gross_yield_pct"] > au["metrics"]["cash_yield_pct"]
        assert intl["score"]["gross_yield_pct"] == pytest.approx(intl["metrics"]["cash_yield_pct"])

    def test_parcels_computed_for_priced_products(self, screened):
        e = by_ticker(screened, "AUEQX")
        assert [p["parcel_aud"] for p in e["parcels"]] == [10_000.0, 25_000.0]
        assert all(p["units"] > 0 for p in e["parcels"])
        assert by_ticker(screened, "NODATA")["parcels"] == []

    def test_high_unit_price_buys_zero_units(self, screened):
        e = by_ticker(screened, "RICHX")
        assert e["parcels"][0]["units"] == 0

    def test_lic_franking_credit_value_is_full_company_rate(self, screened):
        e = by_ticker(screened, "LICX")
        cash = e["metrics"]["cash_yield_pct"]
        assert e["score"]["franking_credit_yield_pct"] == pytest.approx(cash * 0.3 / 0.7)


# ---------------------------------------------------------------------------
# Illustrative structures
# ---------------------------------------------------------------------------

class TestAllocateParcels:
    def test_largest_remainder_sums_to_n(self):
        alloc = ss.allocate_parcels(ss.TEMPLATES["balanced"], 6)
        assert sum(alloc.values()) == 6
        assert alloc == {"cash": 1, "defensive": 2, "core_au": 1, "core_intl": 1, "diversifier": 1}

    def test_small_n_drops_small_roles(self):
        assert ss.allocate_parcels(ss.TEMPLATES["simple"], 3) == {"defensive": 1, "all_in_one": 2}

    def test_one_parcel_goes_to_largest_weight(self):
        assert ss.allocate_parcels(ss.TEMPLATES["conservative"], 1) == {"defensive": 1}

    def test_zero_parcels_rejected(self):
        with pytest.raises(ss.ScreenerError):
            ss.allocate_parcels(ss.TEMPLATES["balanced"], 0)


class TestIllustrate:
    def test_lines_match_allocation(self, screened):
        ill = ss.illustrate(screened, "balanced", 6, 15_000.0, brokerage_aud=10.0, balance_aud=500_000.0, age=60)
        assert len(ill["lines"]) == 6
        assert ill["unfilled_roles"] == []
        assert {l["role"] for l in ill["lines"]} == set(ill["parcels_by_role"])
        assert all(l["units"] > 0 for l in ill["lines"])
        assert 0 < ill["defensive_share_pct"] < 100
        dc = ill["drawdown_cover"]
        assert dc["minimum_factor_pct"] == 4.0
        assert dc["annual_minimum_aud"] == pytest.approx(20_000.0)
        defensive = sum(l["value_aud"] for l in ill["lines"] if l["role"] in ("cash", "defensive"))
        assert dc["years_covered_by_cash_and_defensive"] == pytest.approx(defensive / 20_000.0)

    def test_unbuyable_product_is_skipped_not_allocated_zero_units(self, screened):
        ill = ss.illustrate(screened, "balanced", 6, 15_000.0)
        assert "RICHX" in ill["skipped_not_marketable"]
        assert all(l["ticker"] != "RICHX" for l in ill["lines"])
        assert any(l["role"] == "diversifier" and l["ticker"] == "GOLDX" for l in ill["lines"])

    def test_role_where_nothing_is_buyable_is_unfilled(self, universe):
        only_rich = [p for p in universe if p["role"] != "diversifier" or p["ticker"] == "RICHX"]
        s = ss.screen(only_rich, str(FIXTURE_DIR), dict(ss.DEFAULT_FILTERS), TODAY, as_of=AS_OF)
        ill = ss.illustrate(s, "balanced", 6, 15_000.0)
        assert ill["unfilled_roles"] == ["diversifier"] and ill["skipped_not_marketable"] == ["RICHX"]
        assert "cannot buy a marketable holding: RICHX" in ss.render_illustration(ill)

    def test_role_without_survivors_is_reported(self, universe):
        thin = [p for p in universe if p["role"] != "diversifier" or p["ticker"] == "TINYX"]
        s = ss.screen(thin, str(FIXTURE_DIR), dict(ss.DEFAULT_FILTERS), TODAY, as_of=AS_OF)
        ill = ss.illustrate(s, "balanced", 6, 15_000.0)
        assert ill["unfilled_roles"] == ["diversifier"]
        assert len(ill["lines"]) == 5

    def test_unknown_template(self, screened):
        with pytest.raises(ss.ScreenerError):
            ss.illustrate(screened, "yolo", 3, 10_000.0)

    def test_many_parcels_cycle_over_top_products(self, screened):
        ill = ss.illustrate(screened, "simple", 10, 10_000.0)
        cash_lines = [l for l in ill["lines"] if l["role"] == "cash"]
        assert cash_lines and cash_lines[0]["ticker"] == "CASHX"


# ---------------------------------------------------------------------------
# Optional fetch (yfinance stubbed; the sandbox forbids the network anyway)
# ---------------------------------------------------------------------------

class _Index:
    def __init__(self, d):
        self._d = d

    def date(self):
        return self._d


class _Series(dict):
    def items(self):
        return [(_Index(k), v) for k, v in dict.items(self)]


class _Frame:
    def __init__(self, rows):
        self._rows = rows
        self.columns = ["Close", "Volume", "Dividends"]

    def __len__(self):
        return len(self._rows)

    def iterrows(self):
        for d, row in self._rows:
            yield _Index(d), row

    def __getitem__(self, key):
        assert key == "Dividends"
        return _Series({d: row["Dividends"] for d, row in self._rows})


class TestFetchHistory:
    def _install_fake(self, monkeypatch, frames):
        import types

        class Ticker:
            def __init__(self, symbol):
                self.symbol = symbol

            def history(self, **kw):
                return frames[self.symbol]

        monkeypatch.setitem(sys.modules, "yfinance", types.SimpleNamespace(Ticker=Ticker))

    def test_writes_csv_layout(self, monkeypatch, tmp_path):
        frames = {
            "VAS.AX": _Frame([
                (date(2026, 1, 2), {"Close": 100.5, "Volume": 1000, "Dividends": 0.0}),
                (date(2026, 1, 5), {"Close": float("nan"), "Volume": 0, "Dividends": 0.0}),
                (date(2026, 1, 6), {"Close": 101.0, "Volume": 2000, "Dividends": 1.25}),
            ]),
            "ZZZ.AX": _Frame([]),
        }
        self._install_fake(monkeypatch, frames)
        result = ss.fetch_history(["VAS", "ZZZ"], str(tmp_path), backend="yfinance")
        assert result == {"fetched": ["VAS"], "empty": ["ZZZ"], "failed": {}}
        prices = ss.load_price_history(str(tmp_path), "VAS")
        assert [(r["date"].isoformat(), r["close"], r["volume"]) for r in prices] == [
            ("2026-01-02", 100.5, 1000.0), ("2026-01-06", 101.0, 2000.0)]
        assert ss.load_distributions(str(tmp_path), "VAS") == [{"date": date(2026, 1, 6), "amount": 1.25}]

    def test_exception_per_ticker_is_reported_not_raised(self, monkeypatch, tmp_path):
        import types

        class Ticker:
            def __init__(self, symbol):
                pass

            def history(self, **kw):
                raise RuntimeError("boom")

        monkeypatch.setitem(sys.modules, "yfinance", types.SimpleNamespace(Ticker=Ticker))
        result = ss.fetch_history(["VAS"], str(tmp_path), backend="yfinance")
        assert result["fetched"] == [] and "RuntimeError" in result["failed"]["VAS"]

    def test_missing_yfinance_is_a_clear_error(self, monkeypatch, tmp_path):
        monkeypatch.setitem(sys.modules, "yfinance", None)
        with pytest.raises(ss.ScreenerError, match="yfinance is not installed"):
            ss.fetch_history(["VAS"], str(tmp_path), backend="yfinance")

    def test_unknown_backend(self, tmp_path):
        with pytest.raises(ss.ScreenerError, match="fetch backend"):
            ss.fetch_history(["VAS"], str(tmp_path), backend="bloomberg")


# Yahoo stamps each daily bar at the session open in UTC. For the ASX in
# January (daylight time, gmtoffset 39600) that is 23:00 UTC the evening
# before: these are the 2026-01-05, 2026-01-06 and 2026-01-07 sessions, and
# without the offset they would land on the wrong (previous) UTC date.
SYDNEY = 39600
STAMPS = [1767567600, 1767654000, 1767740400]


def yahoo_payload(closes, volumes, dividends=None, offset=SYDNEY):
    return {"chart": {"result": [{
        "meta": {"symbol": "VAS.AX", "gmtoffset": offset},
        "timestamp": STAMPS[:len(closes)],
        "indicators": {"quote": [{"close": closes, "volume": volumes}]},
        "events": {"dividends": dividends or {}},
    }], "error": None}}


class TestParseYahooChart:
    def test_rows_and_dividends_in_sydney_dates(self):
        payload = yahoo_payload([100.5, None, 101.0], [1000, None, 2000],
                                {"1767747600": {"amount": 1.25, "date": 1767747600}})
        rows, divs = ss.parse_yahoo_chart(payload)
        assert [(r["date"].isoformat(), r["close"], r["volume"]) for r in rows] == [
            ("2026-01-05", 100.5, 1000.0), ("2026-01-07", 101.0, 2000.0)]
        assert divs == [{"date": date(2026, 1, 7), "amount": 1.25}]

    def test_offset_moves_the_date(self):
        # Without the exchange offset the same stamps fall on the previous UTC day.
        rows, _ = ss.parse_yahoo_chart(yahoo_payload([1.0], [1], offset=0))
        assert rows[0]["date"] == date(2026, 1, 4)

    def test_error_and_bad_shape(self):
        with pytest.raises(ss.ScreenerError, match="Yahoo error: No data"):
            ss.parse_yahoo_chart({"chart": {"result": None, "error": {"code": "Not Found", "description": "No data"}}})
        with pytest.raises(ss.ScreenerError, match="unexpected shape"):
            ss.parse_yahoo_chart({"chart": {"result": [{"meta": {}}]}})
        with pytest.raises(ss.ScreenerError, match="unexpected shape"):
            ss.parse_yahoo_chart("not json at all")

    def test_zero_and_junk_dividends_skipped(self):
        payload = yahoo_payload([1.0], [1], {"a": {"amount": 0, "date": STAMPS[0]}, "b": {"amount": "x"},
                                             "c": {"amount": 0.5, "date": STAMPS[0]}})
        _, divs = ss.parse_yahoo_chart(payload)
        assert divs == [{"date": date(2026, 1, 5), "amount": 0.5}]

    def test_no_timestamps_means_no_rows(self):
        payload = yahoo_payload([], [])
        assert ss.parse_yahoo_chart(payload) == ([], [])


class TestFetchHistoryYahoo:
    def test_writes_files_and_reports_failures(self, monkeypatch, tmp_path):
        calls = []

        def fake_get(url, timeout=20.0):
            calls.append(url)
            if "VAS.AX" in url:
                return yahoo_payload([100.5, 100.0, 101.0], [1000, 500, 2000],
                                     {"x": {"amount": 1.25, "date": STAMPS[2]}})
            if "ZZZ.AX" in url:
                return yahoo_payload([], [])
            raise ss.ScreenerError("HTTP 404 from https://query2.finance.yahoo.com/v8/finance/chart/BAD.AX")

        monkeypatch.setattr(ss, "_http_get_json", fake_get)
        monkeypatch.setattr(ss.time, "sleep", lambda s: None)
        result = ss.fetch_history(["VAS", "ZZZ", "BAD"], str(tmp_path), years=3)
        assert result["fetched"] == ["VAS"] and result["empty"] == ["ZZZ"]
        assert "HTTP 404" in result["failed"]["BAD"]
        assert all("range=3y" in u and "events=div" in u and u.endswith("false") for u in calls)
        prices = ss.load_price_history(str(tmp_path), "VAS")
        assert [(r["date"].isoformat(), r["close"]) for r in prices] == [
            ("2026-01-05", 100.5), ("2026-01-06", 100.0), ("2026-01-07", 101.0)]
        assert ss.load_distributions(str(tmp_path), "VAS") == [{"date": date(2026, 1, 7), "amount": 1.25}]
        assert not (tmp_path / "ZZZ.csv").exists()

    def test_http_errors_are_screener_errors(self, monkeypatch):
        import urllib.error
        import urllib.request

        def raise_429(req, timeout=0):
            raise urllib.error.HTTPError(req.full_url, 429, "Too Many Requests", {}, None)

        monkeypatch.setattr(urllib.request, "urlopen", raise_429)
        with pytest.raises(ss.ScreenerError, match="HTTP 429 .*rate limited"):
            ss._http_get_json("https://example.invalid/chart/VAS.AX?range=3y")

        def raise_ssl(req, timeout=0):
            raise urllib.error.URLError("[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed")

        monkeypatch.setattr(urllib.request, "urlopen", raise_ssl)
        with pytest.raises(ss.ScreenerError, match="Install Certificates"):
            ss._http_get_json("https://example.invalid/chart/VAS.AX")

    def test_fetch_only_cli(self, monkeypatch, tmp_path, capsys):
        monkeypatch.setattr(ss, "_http_get_json", lambda url, timeout=20.0: yahoo_payload([50.0] * 3, [100] * 3))
        monkeypatch.setattr(ss.time, "sleep", lambda s: None)
        code = ss.main(["--universe", str(UNIVERSE), "--data-dir", str(tmp_path / "d"), "--fetch-only",
                        "--only-role", "cash"])
        err = capsys.readouterr().err
        assert code == 0 and "fetched 2 of 2" in err
        assert (tmp_path / "d" / "CASHX.csv").exists() and (tmp_path / "d" / "CASHY.dividends.csv").exists()


# ---------------------------------------------------------------------------
# Command line
# ---------------------------------------------------------------------------

BASE_ARGS = ["--universe", str(UNIVERSE), "--data-dir", str(FIXTURE_DIR), "--today", "2026-09-06",
             "--as-of", "2026-09-04"]


def run_cli(capsys, *extra):
    code = ss.main(BASE_ARGS + list(extra))
    captured = capsys.readouterr()
    return code, captured.out, captured.err


class TestCli:
    def test_default_run_prints_disclaimer_and_tables(self, capsys):
        code, out, err = run_cli(capsys)
        assert code == 0
        assert out.startswith("GENERAL INFORMATION ONLY")
        assert out.rstrip().endswith("NOT PERSONAL FINANCIAL ADVICE.")
        for role in ss.ROLES:
            assert f"== {ss.ROLE_LABELS[role]} ==" in out
        assert "excluded: no price history" in out
        assert "universe check: OLDFCT" in err

    def test_hide_excluded(self, capsys):
        code, out, _ = run_cli(capsys, "--hide-excluded")
        assert code == 0 and "NODATA" not in out and "CASHX" in out

    def test_explain_shows_arithmetic(self, capsys):
        code, out, _ = run_cli(capsys, "--explain", "aueqx")
        assert code == 0
        assert "grossed-up yield" in out and "x weight" in out and "score" in out
        assert "AUD 10,000 parcel" in out

    def test_explain_unknown_ticker(self, capsys):
        code, _, err = run_cli(capsys, "--explain", "ZZZ")
        assert code == 2 and "not in the universe" in err

    def test_illustrate_and_outputs(self, capsys, tmp_path):
        j = tmp_path / "out.json"
        md = tmp_path / "out.md"
        code, out, _ = run_cli(capsys, "--illustrate", "balanced", "--n-parcels", "6", "--parcel", "15000",
                               "--balance", "500000", "--json", str(j), "--markdown", str(md))
        assert code == 0
        assert "Illustrative structure 'balanced'" in out
        assert "cover 1" in out or "years of it" in out
        payload = json.loads(j.read_text())
        assert payload["as_of"] == "2026-09-04"
        assert payload["illustration"]["template"] == "balanced"
        assert len(payload["results"]) == 18
        text = md.read_text()
        assert text.startswith("# SMSF screener output") and "| CASHX |" in text

    def test_single_parcel_flag(self, capsys):
        code, out, _ = run_cli(capsys, "--parcel", "20000")
        assert code == 0 and "u@20k" in out and "u@10k" not in out

    def test_bad_parcel(self, capsys):
        code, _, err = run_cli(capsys, "--parcel", "-5")
        assert code == 2 and "must be positive" in err

    def test_only_role_and_exclude(self, capsys):
        code, out, _ = run_cli(capsys, "--only-role", "cash", "--exclude", "cashy")
        assert code == 0 and "CASHX" in out and "CASHY" not in out and "AUEQX" not in out

    def test_exclude_everything(self, capsys):
        code, _, err = run_cli(capsys, "--only-role", "cash", "--exclude", "CASHX", "--exclude", "CASHY")
        assert code == 2 and "no products left" in err

    def test_audit_universe_reports_and_exits_nonzero(self, capsys):
        code, out, _ = run_cli(capsys, "--audit-universe")
        assert code == 1 and "OLDFCT" in out

    def test_audit_real_universe_is_clean(self, capsys):
        code = ss.main(["--universe", str(REAL_UNIVERSE), "--data-dir", str(FIXTURE_DIR),
                        "--today", "2026-09-06", "--audit-universe"])
        assert code == 0
        assert "no anomalies" in capsys.readouterr().out

    def test_rules_prints_policy(self, capsys):
        assert ss.main(["--rules"]) == 0
        out = capsys.readouterr().out
        assert "MER cap" in out and "balanced" in out and "95+ 14%" in out

    def test_missing_data_dir(self, capsys, tmp_path):
        code = ss.main(["--universe", str(UNIVERSE), "--data-dir", str(tmp_path / "nope"), "--today", "2026-09-06"])
        assert code == 2 and "data directory not found" in capsys.readouterr().err

    def test_empty_data_dir(self, capsys, tmp_path):
        code = ss.main(["--universe", str(UNIVERSE), "--data-dir", str(tmp_path), "--today", "2026-09-06"])
        assert code == 2 and "no price history found" in capsys.readouterr().err

    def test_fetch_without_yfinance(self, capsys, monkeypatch, tmp_path):
        monkeypatch.setitem(sys.modules, "yfinance", None)
        code = ss.main(["--universe", str(UNIVERSE), "--data-dir", str(tmp_path), "--fetch-only",
                        "--fetch-backend", "yfinance"])
        assert code == 2 and "yfinance is not installed" in capsys.readouterr().err

    def test_bad_dates(self, capsys):
        code = ss.main(["--universe", str(UNIVERSE), "--data-dir", str(FIXTURE_DIR), "--today", "6/9/2026"])
        assert code == 2 and "--today" in capsys.readouterr().err

    def test_stale_data_warning(self, capsys):
        code = ss.main(["--universe", str(UNIVERSE), "--data-dir", str(FIXTURE_DIR), "--today", "2026-12-01",
                        "--as-of", "2026-09-04"])
        assert code == 0 and "price data is 88 days old" in capsys.readouterr().out


class TestRendering:
    def test_json_is_sorted_and_round_trips_dates(self, screened):
        payload = json.loads(ss.to_json(screened))
        assert payload["today"] == "2026-09-06"
        assert payload["results"][0]["product"]["as_at"] == "2026-06-30"

    def test_markdown_has_a_row_per_product(self, screened):
        text = ss.render_markdown(screened)
        for e in screened["results"]:
            assert f"| {e['product']['ticker']} |" in text

    def test_text_output_is_ascii_safe(self, screened):
        ss.render_text(screened).encode("ascii")
